### ISSUE TITLE
Multiplayer?

### ISSUE THREAD

**Issue by naxIO** [livinamuk/Hell2025#11]
Hey man,

this is a great project and I understand its very early and an FPS Tech Demo right now. 

Would you be interested to implement Multiplayer at some point as a challenge? Using a middleware like Raknet or so? Interested to hear your general thoughts on this! 

Keep on rocking!

**Comment by 90th** [comment]
There's currently a split-screen implemented.

**Comment by naxIO** [comment]
Thanks, will wait what will happen!
