### ISSUE TITLE
this prob isnt right

### ISSUE THREAD

**Issue by jereremy** [livinamuk/Hell2025#18]
https://github.com/livinamuk/Hell2024/blob/45309d2e37050e37a866bf680d753cd4374542c6/Hell2024/Hell2024/src/Core/Player.cpp#L924

**Comment by livinamuk** [comment]
Cheers, I must have pasted that by mistake. That code can actually never run because the flags RELOAD and RELOAD_FROM_EMPTY are never set when you have the shotgun out, it uses different ones. Thanks for pointing it out, I've deleted it now.

**Comment by livinamuk** [comment]
Fixed
