### ISSUE TITLE
Corrupt .lib files

### ISSUE THREAD

**Issue by wonganingoma** [livinamuk/Hell2025#26]
All .lib files in vendor are corrupt, all of them are about 1kb, and the linker gives error LNK:1107 when trying to link to any one of them.

**Comment by livinamuk** [comment]
I'm using LFS aka Large File System for all lib files so you need to download via terminal with
```
git clone https://github.com/livinamuk/Hell2024.git
```
been meaning to update the readme

**Comment by livinamuk** [comment]
Pushed changes and updated readme with instructions.
