### ISSUE TITLE
Networking (Suggestion)

### ISSUE THREAD

**Issue by backfromhiatus** [livinamuk/Hell2025#5]
https://github.com/meemknight/multiPlayerGame
this is a good example of basic P2P networking
you can also steal the glUI library to make a funny menu to make the game complete (the library is in the thirdparty directory)
https://github.com/KernelOverseer/KSICARDOOM
this is also something I found that has networking

**Comment by livinamuk** [comment]
Cheers, I've done basic networking before, the reason I'm putting it off is because designing a system that works efficient enough to support online deathmatch is a huge task. I've been working on UI today actually!

**Comment by backfromhiatus** [comment]
Ah nice to know.
