### ISSUE TITLE
Knife Distance

### ISSUE THREAD

**Issue by EIonv** [livinamuk/Hell2025#7]
this is not really an issue but I noticed that the knife distance was infinite so I just added this in the Knife section:
![image](https://github.com/livinamuk/Hell2024/assets/102845355/e4987e32-2d22-4ec9-a66e-164774664db0)

**Comment by livinamuk** [comment]
Cheers, that's a good way to handle it. I've been neglecting the knife, waiting till I have some good knife mark decals before polishing it off.

**Comment by EIonv** [comment]
Thank you, I'm sure you'd be able to make this much cleaner. Once you get the decals for the knife marks it will be perfect if not close to perfect.
